packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages_work/*'
  - 'common/**'
  - 'ci___/**'
  # all packages in subdirs of components/
  # exclude packages that are inside test directories
  - '!**/test/**'

