import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
// import { VideoPlayer0 } from "../components/videoPlayer0";
import LoginPage from "../../components/login";
import VideoPlayer, { SAMPLE_VIDEOS } from "../../components/videoPlayer";
import { Lang } from "../../middleware";
import { getDictionary } from "./dictionaries";






export default async function Home({
  params,
}: {
  params: Promise<{ lang: Lang; }>;
}) {
  return (
    <div className="w-screen h-screen">
      <RsizeContainer lang={(await params).lang} />
    </div>
  );
}
const main_len = 50;
const RsizeContainer = async ({ lang }: { lang: Lang; }) => {
  const ass = getAss();
  const dict = await getDictionary(lang); // en
  return <ResizablePanelGroup
    direction="horizontal"
    className="w-screen rounded-lg border">
    <ResizablePanel defaultSize={main_len}>
      <div className="flex h-screen justify-center">
        <VideoPlayer videos={SAMPLE_VIDEOS} ></VideoPlayer>
      </div>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={(100 - main_len) / 2}>
      <Tabs
        defaultValue="captions"
        className="w-full h-screen max-h-screen flex flex-col overflow-hidden pt-2 pb-2 "
      >
        <TabsList className="pl-2 pr-2 bg-transparent w-full">
          <TabsTrigger value="captions">{dict.products.subtitles}</TabsTrigger>
          <TabsTrigger value="trend">{dict.products.trend}</TabsTrigger>
          <TabsTrigger value="mine">{dict.products.my}</TabsTrigger>
          <div className="w-full"></div>
          <TabsTrigger value="upload">{dict.products.upload}</TabsTrigger>
        </TabsList>
        <TabsContent
          value="captions"
          className="flex-1 overflow-hidden flex flex-col"
        >
          <ScrollArea className="flex-1 w-full overflow-hidden p-2">
            <div className="flex flex-col">
              {[...ass, ...ass, ...ass].map((e, i) => {
                return <div key={i}>{e.Text}</div>;
              })}
            </div>
            <ScrollBar className="w-0 "></ScrollBar>
          </ScrollArea>
        </TabsContent>
        <TabsContent value="trend" className="p-2 flex-1 overflow-hidden">
          {dict.products.trend}
        </TabsContent>
        <TabsContent value="mine" className="p-2 flex-1 overflow-hidden">
          {dict.products.my}
        </TabsContent>
        <TabsContent value="upload" className="p-2 flex-1 overflow-hidden">
          {dict.products.upload}
        </TabsContent>
      </Tabs>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={(100 - main_len) / 2}>
      <div className="flex h-screen items-center justify-center p-6">
        <LoginPage></LoginPage>
      </div>
    </ResizablePanel>
  </ResizablePanelGroup >;
};





function getAss() {
  const abc = `
[Script Info]
; Script generated by ChatGPT
Title: Example Subtitle
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
WrapStyle: 0
YCbCr Matrix: TV.601

[Aegisub Project Garbage]
Last Style Storage: Default
Audio File: ?audio
Video File: ?video

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:04.00,Default,,0,0,0,,Hello, this is an example subtitle.
Dialogue: 0,0:00:05.00,0:00:08.00,Default,,0,0,0,,这是第二行字幕，带中文。
Dialogue: 0,0:00:09.00,0:00:12.00,Default,,0,0,0,,第三行字幕 ~ with English mix.
Dialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,Hello everyone, welcome to this demo!
Dialogue: 0,0:00:05.50,0:00:09.00,Default,,0,0,0,,大家好，欢迎来到字幕演示。
Dialogue: 0,0:00:09.50,0:00:13.00,Default,,0,0,0,,This is line number three, simple and clear.
Dialogue: 0,0:00:13.50,0:00:17.00,Default,,0,0,0,,这是第四行字幕，展示多语言支持。
Dialogue: 0,0:00:17.50,0:00:21.00,Default,,0,0,0,,Line five: testing longer sentences to see wrapping.
Dialogue: 0,0:00:21.50,0:00:25.00,Default,,0,0,0,,第六行：测试更长的中文句子，看看换行效果。
Dialogue: 0,0:00:25.50,0:00:29.00,Default,,0,0,0,,Line seven: Mixing 中文 and English smoothly.
Dialogue: 0,0:00:29.50,0:00:33.00,Default,,0,0,0,,第八行：让字幕显示更自然。
Dialogue: 0,0:00:33.50,0:00:37.00,Default,,0,0,0,,Line nine: Almost done, keep watching.
Dialogue: 0,0:00:37.50,0:00:41.00,Default,,0,0,0,,第十行：字幕演示结束，谢谢观看！
Dialogue: 0,0:00:01.00,0:00:04.00,Default,,0,0,0,,Line 1: Hello, this is a demo subtitle.
Dialogue: 0,0:00:04.00,0:00:07.00,Default,,0,0,0,,第2行：这是一个演示字幕。
Dialogue: 0,0:00:07.00,0:00:10.00,Default,,0,0,0,,Line 3: Subtitles are useful for videos.
Dialogue: 0,0:00:10.00,0:00:13.00,Default,,0,0,0,,第4行：字幕对视频非常有用。
Dialogue: 0,0:00:13.00,0:00:16.00,Default,,0,0,0,,Line 5: They help people understand better.
Dialogue: 0,0:00:16.00,0:00:19.00,Default,,0,0,0,,第6行：它们能帮助人们更好理解。
Dialogue: 0,0:04:52.00,0:04:55.00,Default,,0,0,0,,Line 99: Almost finished, this is near the end.
Dialogue: 0,0:04:55.00,0:04:58.00,Default,,0,0,0,,第100行：终于到最后啦，谢谢观看！
`;

  type AssEvent = {
    Layer: string;
    Start: string;
    End: string;
    Style: string;
    Name: string;
    MarginL: string;
    MarginR: string;
    MarginV: string;
    Effect: string;
    Text: string;
  };

  function assToJson(assText: string): AssEvent[] {
    const lines = assText.split(/\r?\n/);

    // 找到 [Events] 部分
    const eventsStart = lines.findIndex(line => line.trim() === "[Events]");
    if (eventsStart === -1) return [];

    // 找到 Format 行
    const formatLine = lines.slice(eventsStart + 1).find(line => line.startsWith("Format:"));
    if (!formatLine) return [];
    const formatFields = formatLine.replace("Format:", "").split(",").map(f => f.trim());

    // 找到 Dialogue 行
    const dialogueLines = lines.slice(eventsStart + 2).filter(line => line.startsWith("Dialogue:"));

    const result: AssEvent[] = dialogueLines.map(line => {
      // 把 "Dialogue:" 去掉
      const raw = line.replace("Dialogue:", "").trim();
      const parts = raw.split(",");

      const entry: Partial<AssEvent> = {};
      for (let i = 0; i < formatFields.length - 1; i++) {
        entry[formatFields[i] as keyof AssEvent] = parts[i]?.trim() ?? "";
      }

      // Text 部分可能包含逗号，需要合并
      entry.Text = parts.slice(formatFields.length - 1).join(",").trim();

      return entry as AssEvent;
    });

    return result;
  }


  return assToJson(abc);
}




