
import { VideoItem } from "@/types";

const ass = `
[Script Info]
; Script generated by ChatGPT
Title: Example Subtitle
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
WrapStyle: 0
YCbCr Matrix: TV.601

[Aegisub Project Garbage]
Last Style Storage: Default
Audio File: ?audio
Video File: ?video

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:04.00,Default,,0,0,0,,Hello, this is an example subtitle.
Dialogue: 0,0:00:05.00,0:00:08.00,Default,,0,0,0,,这是第二行字幕，带中文。
Dialogue: 0,0:00:09.00,0:00:12.00,Default,,0,0,0,,第三行字幕 ~ with English mix.
Dialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,Hello everyone, welcome to this demo!
Dialogue: 0,0:00:05.50,0:00:09.00,Default,,0,0,0,,大家好，欢迎来到字幕演示。
Dialogue: 0,0:00:09.50,0:00:13.00,Default,,0,0,0,,This is line number three, simple and clear.
Dialogue: 0,0:00:13.50,0:00:17.00,Default,,0,0,0,,这是第四行字幕，展示多语言支持。
Dialogue: 0,0:00:17.50,0:00:21.00,Default,,0,0,0,,Line five: testing longer sentences to see wrapping.
Dialogue: 0,0:00:21.50,0:00:25.00,Default,,0,0,0,,第六行：测试更长的中文句子，看看换行效果。
Dialogue: 0,0:00:25.50,0:00:29.00,Default,,0,0,0,,Line seven: Mixing 中文 and English smoothly.
Dialogue: 0,0:00:29.50,0:00:33.00,Default,,0,0,0,,第八行：让字幕显示更自然。
Dialogue: 0,0:00:33.50,0:00:37.00,Default,,0,0,0,,Line nine: Almost done, keep watching.
Dialogue: 0,0:00:37.50,0:00:41.00,Default,,0,0,0,,第十行：字幕演示结束，谢谢观看！
Dialogue: 0,0:00:01.00,0:00:04.00,Default,,0,0,0,,Line 1: Hello, this is a demo subtitle.
Dialogue: 0,0:00:04.00,0:00:07.00,Default,,0,0,0,,第2行：这是一个演示字幕。
Dialogue: 0,0:00:07.00,0:00:10.00,Default,,0,0,0,,Line 3: Subtitles are useful for videos.
Dialogue: 0,0:00:10.00,0:00:13.00,Default,,0,0,0,,第4行：字幕对视频非常有用。
Dialogue: 0,0:00:13.00,0:00:16.00,Default,,0,0,0,,Line 5: They help people understand better.
Dialogue: 0,0:00:16.00,0:00:19.00,Default,,0,0,0,,第6行：它们能帮助人们更好理解。
Dialogue: 0,0:04:52.00,0:04:55.00,Default,,0,0,0,,Line 99: Almost finished, this is near the end.
Dialogue: 0,0:04:55.00,0:04:58.00,Default,,0,0,0,,第100行：终于到最后啦，谢谢观看！
`;

type AssEvent = {
  Layer: string;
  Start: string;
  End: string;
  Style: string;
  Name: string;
  MarginL: string;
  MarginR: string;
  MarginV: string;
  Effect: string;
  Text: string;
};

function assToJson(assText: string): AssEvent[] {
  const lines = assText.split(/\r?\n/);

  // 找到 [Events] 部分
  const eventsStart = lines.findIndex(line => line.trim() === "[Events]");
  if (eventsStart === -1) return [];

  // 找到 Format 行
  const formatLine = lines.slice(eventsStart + 1).find(line => line.startsWith("Format:"));
  if (!formatLine) return [];
  const formatFields = formatLine.replace("Format:", "").split(",").map(f => f.trim());

  // 找到 Dialogue 行
  const dialogueLines = lines.slice(eventsStart + 2).filter(line => line.startsWith("Dialogue:"));

  const result: AssEvent[] = dialogueLines.map(line => {
    // 把 "Dialogue:" 去掉
    const raw = line.replace("Dialogue:", "").trim();
    const parts = raw.split(",");

    const entry: Partial<AssEvent> = {};
    for (let i = 0; i < formatFields.length - 1; i++) {
      entry[formatFields[i] as keyof AssEvent] = parts[i]?.trim() ?? "";
    }

    // Text 部分可能包含逗号，需要合并
    entry.Text = parts.slice(formatFields.length - 1).join(",").trim();

    return entry as AssEvent;
  });

  return result;
}


/* ----------------- 示例数据 ----------------- */
export const SAMPLE_VIDEOS: VideoItem[] = [
  {
    id: 1,
    src: "英语学习【奇幻沼泽第一季~第三季】 p02 第一季2拐杖风波 [BV1XUbtzsEJT_p2].mp4",
    title: "第一季2拐杖风波",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 2,
    src: "英语学习【奇幻沼泽第一季~第三季】 p03 第一季3跳爷爷的料理 [BV1XUbtzsEJT_p3].mp4",
    title: "第一季3跳爷爷的料理",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 3,
    src: "英语学习【奇幻沼泽第一季~第三季】 p04 第一季4多米诺效应 [BV1XUbtzsEJT_p4].mp4",
    title: "第一季4多米诺效应",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 4,
    src: "英语学习【奇幻沼泽第一季~第三季】 p05 第一季5侠盗猎车手小安 [BV1XUbtzsEJT_p5].mp4",
    title: "第一季5侠盗猎车手小安",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 5,
    src: "英语学习【奇幻沼泽第一季~第三季】 p06 第一季6盆盆大战跳爷爷 [BV1XUbtzsEJT_p6].mp4",
    title: "第一季6盆盆大战跳爷爷",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 6,
    src: "英语学习【奇幻沼泽第一季~第三季】 p07 第一季7约会季 [BV1XUbtzsEJT_p7].mp4",
    title: "第一季7约会季",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 7,
    src: "英语学习【奇幻沼泽第一季~第三季】 p08 第一季8红腿病风波 [BV1XUbtzsEJT_p8].mp4",
    title: "第一季8红腿病风波",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 8,
    src: "英语学习【奇幻沼泽第一季~第三季】 p09 第一季9莲叶泰食 [BV1XUbtzsEJT_p9].mp4",
    title: "第一季9莲叶泰食",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 9,
    src: "英语学习【奇幻沼泽第一季~第三季】 p10 第一季10蟾蜍税 [BV1XUbtzsEJT_p10].mp4",
    title: "第一季10蟾蜍税",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 10,
    src: "英语学习【奇幻沼泽第一季~第三季】 p11 第一季11毛猪虫之日 [BV1XUbtzsEJT_p11].mp4",
    title: "第一季11毛猪虫之日",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 11,
    src: "英语学习【奇幻沼泽第一季~第三季】 p12 第一季12手足党争 [BV1XUbtzsEJT_p12].mp4",
    title: "第一季12手足党争",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 12,
    src: "英语学习【奇幻沼泽第一季~第三季】 p13 第一季13闹与罚 [BV1XUbtzsEJT_p13].mp4",
    title: "第一季13闹与罚",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 13,
    src: "英语学习【奇幻沼泽第一季~第三季】 p14 第一季14下雪天 [BV1XUbtzsEJT_p14].mp4",
    title: "第一季14下雪天",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 14,
    src: "英语学习【奇幻沼泽第一季~第三季】 p15 第一季15雨夜惊魂 [BV1XUbtzsEJT_p15].mp4",
    title: "第一季15雨夜惊魂",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 15,
    src: "英语学习【奇幻沼泽第一季~第三季】 p16 第一季16家庭钓鱼之旅 [BV1XUbtzsEJT_p16].mp4",
    title: "第一季16家庭钓鱼之旅",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 16,
    src: "英语学习【奇幻沼泽第一季~第三季】 p17 第一季17你被诅咒了 [BV1XUbtzsEJT_p17].mp4",
    title: "第一季17你被诅咒了",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 17,
    src: "英语学习【奇幻沼泽第一季~第三季】 p18 第一季18虫虫球大战 [BV1XUbtzsEJT_p18].mp4",
    title: "第一季18虫虫球大战",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 18,
    src: "英语学习【奇幻沼泽第一季~第三季】 p19 第一季19孢子的孩子 [BV1XUbtzsEJT_p19].mp4",
    title: "第一季19孢子的孩子",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 19,
    src: "英语学习【奇幻沼泽第一季~第三季】 p20 第一季20重聚 [BV1XUbtzsEJT_p20].mp4",
    title: "第一季20重聚",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 20,
    src: "英语学习【奇幻沼泽第一季~第三季】 p21 第二季1大展身手的小安 [BV1XUbtzsEJT_p21].mp4",
    title: "第二季1大展身手的小安",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 21,
    src: "英语学习【奇幻沼泽第一季~第三季】 p22 第二季2跳爷爷的颂歌 [BV1XUbtzsEJT_p22].mp4",
    title: "第二季2跳爷爷的颂歌",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 22,
    src: "英语学习【奇幻沼泽第一季~第三季】 p23 第二季3休息站的泡泡 [BV1XUbtzsEJT_p23].mp4",
    title: "第二季3休息站的泡泡",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 23,
    src: "英语学习【奇幻沼泽第一季~第三季】 p24 第二季4争吵者之路 [BV1XUbtzsEJT_p24].mp4",
    title: "第二季4争吵者之路",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 24,
    src: "英语学习【奇幻沼泽第一季~第三季】 p25 第二季5沼泽与情感 [BV1XUbtzsEJT_p25].mp4",
    title: "第二季5沼泽与情感",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 25,
    src: "英语学习【奇幻沼泽第一季~第三季】 p26 第二季6大门前的玛茜 [BV1XUbtzsEJT_p26].mp4",
    title: "第二季6大门前的玛茜",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 26,
    src: "英语学习【奇幻沼泽第一季~第三季】 p27 第二季7寻字之旅 [BV1XUbtzsEJT_p27].mp4",
    title: "第二季7寻字之旅",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 27,
    src: "英语学习【奇幻沼泽第一季~第三季】 p28 第二季8迷失理想国 [BV1XUbtzsEJT_p28].mp4",
    title: "第二季8迷失理想国",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 28,
    src: "英语学习【奇幻沼泽第一季~第三季】 p29 第二季9蛙蛙小镇 [BV1XUbtzsEJT_p29].mp4",
    title: "第二季9蛙蛙小镇",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 29,
    src: "英语学习【奇幻沼泽第一季~第三季】 p30 第二季10终极睡衣派对 [BV1XUbtzsEJT_p30].mp4",
    title: "第二季10终极睡衣派对",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 30,
    src: "英语学习【奇幻沼泽第一季~第三季】 p31 第二季11万宅夜 [BV1XUbtzsEJT_p31].mp4",
    title: "第二季11万宅夜",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 31,
    src: "英语学习【奇幻沼泽第一季~第三季】 p32 第二季12夜车司机 [BV1XUbtzsEJT_p32].mp4",
    title: "第二季12夜车司机",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 32,
    src: "英语学习【奇幻沼泽第一季~第三季】 p33 第二季13逃跑的艾薇 [BV1XUbtzsEJT_p33].mp4",
    title: "第二季13逃跑的艾薇",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 33,
    src: "英语学习【奇幻沼泽第一季~第三季】 p34 第二季14第一座神庙 [BV1XUbtzsEJT_p34].mp4",
    title: "第二季14第一座神庙",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 34,
    src: "英语学习【奇幻沼泽第一季~第三季】 p35 第二季15新树瘤丛林 [BV1XUbtzsEJT_p35].mp4",
    title: "第二季15新树瘤丛林",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 35,
    src: "英语学习【奇幻沼泽第一季~第三季】 p36 第二季17第二座神庙 [BV1XUbtzsEJT_p36].mp4",
    title: "第二季17第二座神庙",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 36,
    src: "英语学习【奇幻沼泽第一季~第三季】 p37 第二季18贝茜和小阿杰洛 [BV1XUbtzsEJT_p37].mp4",
    title: "第二季18贝茜和小阿杰洛",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 37,
    src: "英语学习【奇幻沼泽第一季~第三季】 p38 第二季19晚宴 [BV1XUbtzsEJT_p38].mp4",
    title: "第二季19晚宴",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 38,
    src: "英语学习【奇幻沼泽第一季~第三季】 p39 第二季20本色终现 [BV1XUbtzsEJT_p39].mp4",
    title: "第二季20本色终现",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 39,
    src: "英语学习【奇幻沼泽第一季~第三季】 p40 第三季1新常态 [BV1XUbtzsEJT_p40].mp4",
    title: "第三季1新常态",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 40,
    src: "英语学习【奇幻沼泽第一季~第三季】 p41 第三季2购物大考验 [BV1XUbtzsEJT_p41].mp4",
    title: "第三季2购物大考验",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 41,
    src: "英语学习【奇幻沼泽第一季~第三季】 p42 第三季3泰国菜之争 [BV1XUbtzsEJT_p42].mp4",
    title: "第三季3泰国菜之争",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 42,
    src: "英语学习【奇幻沼泽第一季~第三季】 p43 第三季4博物馆决战夜 [BV1XUbtzsEJT_p43].mp4",
    title: "第三季4博物馆决战夜",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 43,
    src: "英语学习【奇幻沼泽第一季~第三季】 p44 第一季5侠盗猎车手小安 [BV1XUbtzsEJT_p44].mp4",
    title: "第一季5侠盗猎车手小安",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 44,
    src: "英语学习【奇幻沼泽第一季~第三季】 p45 第三季6X先生 [BV1XUbtzsEJT_p45].mp4",
    title: "第三季6X先生",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 45,
    src: "英语学习【奇幻沼泽第一季~第三季】 p46 第三季7蛙蛙侠盆盆 [BV1XUbtzsEJT_p46].mp4",
    title: "第三季7蛙蛙侠盆盆",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 46,
    src: "英语学习【奇幻沼泽第一季~第三季】 p47 第三季8好莱坞的跳爷爷 [BV1XUbtzsEJT_p47].mp4",
    title: "第三季8好莱坞的跳爷爷",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 47,
    src: "英语学习【奇幻沼泽第一季~第三季】 p48 第三季9小小蛙蛙过圣诞 [BV1XUbtzsEJT_p48].mp4",
    title: "第三季9小小蛙蛙过圣诞",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 48,
    src: "英语学习【奇幻沼泽第一季~第三季】 p49 第三季10逃回奇幻沼泽 [BV1XUbtzsEJT_p49].mp4",
    title: "第三季10逃回奇幻沼泽",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 49,
    src: "英语学习【奇幻沼泽第一季~第三季】 p50 第三季11司令官小安 [BV1XUbtzsEJT_p50].mp4",
    title: "第三季11司令官小安",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 50,
    src: "英语学习【奇幻沼泽第一季~第三季】 p51 第三季12萨莎的霹雳娇娃 [BV1XUbtzsEJT_p51].mp4",
    title: "第三季12萨莎的霹雳娇娃",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 51,
    src: "英语学习【奇幻沼泽第一季~第三季】 p52 第三季13洞螈之母 [BV1XUbtzsEJT_p52].mp4",
    title: "第三季13洞螈之母",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 52,
    src: "英语学习【奇幻沼泽第一季~第三季】 p53 第三季14邪恶之根 [BV1XUbtzsEJT_p53].mp4",
    title: "第三季14邪恶之根",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 53,
    src: "英语学习【奇幻沼泽第一季~第三季】 p54 第三季15蝾螈也疯狂 [BV1XUbtzsEJT_p54].mp4",
    title: "第三季15蝾螈也疯狂",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 54,
    src: "英语学习【奇幻沼泽第一季~第三季】 p55 第三季16三军会师 [BV1XUbtzsEJT_p55].mp4",
    title: "第三季16三军会师",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 55,
    src: "英语学习【奇幻沼泽第一季~第三季】 p56 第三季17 [BV1XUbtzsEJT_p56].mp4",
    title: "第三季17",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  },
  {
    id: 56,
    src: "英语学习【奇幻沼泽第一季~第三季】 p57 第三季18世间最艰难之事 完 [BV1XUbtzsEJT_p57].mp4",
    title: "第三季18世间最艰难之事 完",
    author: "bunny",
    likes: 13200,
    comments: 560,
    shares: 120,
    avatar: "https://i.pravatar.cc/100?img=1"
  }
];


export const MOCK_SAMPLE_ASS = assToJson(ass);
export const MOCK_SAMPLE_VIDEOS = SAMPLE_VIDEOS;